INSERT INTO public.users (
    role,
    login,
    password,
    name,
    surname,
    patronymic,
    phone,
    email,
    inn,
    time_zone,
    locale,
    bank_bik,
    bank_acc,
    birthdate,
    address_reg,
    passport,
    equipments,
    ycl_staff_id,
    agent_percent,
    speciality_id,
    studio_id,
    passport_main,
    passport_registration,
    photo_front,
    registration_status
) VALUES (
    'admin',
    'admin_login',
    'hashed_password_here',
    'Иван',
    'Иванов',
    'Иванович',
    '+79123456789',
    'artem.volcano@gmail.com',
    '123456789012',
    'UTC+3',
    'ru',
    '044525999',
    '40817810099910000001',
    '1990-01-01',
    'ул. Пушкина, д. 10, г. Москва',
    '{"series": "1234", "number": "567890", "issued_by": "МВД Москвы", "issue_date": "2015-05-05"}'::JSONB,
    '[{"id": 1, "name": "Canon EOS 5D Mark IV"}]'::JSONB,
    123456,
    10.50,
    1,
    1,
    'https://example.com/passport_main.jpg',
    'https://example.com/passport_registration.jpg',
    'https://example.com/photo_front.jpg',
    'confirmed'
);